# Generated by Django 6.1.1 on 2026-09-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='upc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
