# Generated by Django 6.1.1 on 2026-09-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_upc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='music.album')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
