# Generated by Django 6.1.1 on 2026-09-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('music', 'Музыка'), ('collab', 'Сотрудничество'), ('other', 'Другое')], max_length=20)),
                ('message', models.TextField()),
                ('reply_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
