# Generated by Django 6.1.1 on 2026-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_photo', models.ImageField(blank=True, upload_to='photos/')),
            ],
        ),
    ]
