# Generated by Django 6.1.1 on 2026-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='album',
            name='release_type',
            field=models.CharField(choices=[('album', 'Альбом'), ('ep', 'Мини-альбом')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='albumlink',
            constraint=models.UniqueConstraint(fields=('album', 'name'), name='unique_service_per_album'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('album', 'number'), name='unique_track_number_per_album'),
        ),
    ]
