# Generated by Django 6.1.1 on 2026-09-12 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_track_options_alter_album_release_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='music.album')),
                ('single', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='music.single')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
